### PR TITLE
Made Lua.get return None if the value is nil, even if the type being …

### PR DESCRIPTION
**Pull request by Ameliorate**
…casted to has a value for nil

This change is slightly more breaking, since it changes behaviour instead of adding.

This is the second concern in #66.

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks!

Could you also change `into_get`, and `get`/`into_get` in lua_tables.rs?

**Comment by Ameliorate** [comment]
The read_nil test was broken by this change, but I'm not entirely sure how to remove it, since it is in a different branch.

**Comment by Ameliorate** [comment]
Okay that either worked or broke everything.

**Comment by tomaka** [comment]
Thanks

**Comment by Ameliorate** [comment]
Could you publish a new version on crates.io. I have a crate that depends on this feature and I can't figure out how to use this package directly from git.

**Pull request merged**
