### PR TITLE
By value captures

### PR DESCRIPTION
**Pull request by tiffany352**
Allows capturing the context by value instead of using a borrow, which is useful for embedding a long-living table in a struct.

### CODE REVIEW

**Comment by tomaka** [comment]
I don't think you should remove the implementations of `AsLua` and `AsMutLua` for references. I'm surprised that the tests are passing.

**Comment by tiffany352** [comment]
I got errors because it created conflicting implementations (for &mut Lua, should it pick the &mut impl and then the Lua impl, or should it pick the &mut Lua impl?). I'm not sure how to resolve the issue otherwise, and I'm not really sure what's so bad about it.

**Comment by TyOverby** [comment]
Would this be something that would be easier to solve when specialization lands?

**Comment by tomaka** [comment]
Ah, sorry, nevermind. I forgot that there was `impl AsLua for &'a T where T: AsLua {}`.

**Pull request merged**
