### PR TITLE
Allow pushing Options

### LINKED ISSUE #124: impl Push for Option<T>
It would be nice if I could return `Option`s from my callbacks, basically "push this value if it exists, otherwise push `nil`". `Result` already supports this, so this seems like a logical addition.

### PR DESCRIPTION
**Pull request by jonas-schievink**
* Some(T) pushes the T
* None pushes `nil`

Closes #124

### CODE REVIEW

**Comment by tomaka** [comment]
I think this should be more generic, no?
With your code you can only use `Option` as the return type of a Rust closure, and I don't see why not allow it in all situations.

**Comment by jonas-schievink** [comment]
Sure, that makes sense. I think I'm beginning to understand how things work :)

**Comment by tomaka** [comment]
Please move the code to `values.rs` instead of `functions_write`, since this is no longer strictly related to functions.

**Comment by tomaka** [comment]
Thanks

**Pull request merged**
