### PR TITLE
Better error type via quick-error (fixes #50)

### LINKED ISSUE #50: LuaError to implement the std::error::Error trait
It would be awesome if hlua::LuaError could implement the std::error::Error trait, as it would make it much smoother to implement error handling.

### PR DESCRIPTION
**Pull request by tailhook**
Basically this adds implementation of `std::error::Error` and `std::fmt::Display`. 

Also added `From` implementation for `IoError`.

### CODE REVIEW

**Comment by mkpankov** [comment]
Apart from being severely outdated, are there other problems in the PR? As I understand, it could fix #50 .

**Comment by tomaka** [comment]
I'm undecided on the benefit of using an external library just to save a few lines of code.

**Comment by mkpankov** [comment]
Would implementing `Error` ourselves w/o use of `quick-error` be better?

**Comment by tomaka** [comment]
Well, that's the problem, I don't know if it's better. I guess I'd more easily merge a PR that implements Error manually.

**Pull request closed without merging**
